APP := "extensions-test"

build:
  cat $(< build-order) > build.qvs

download:
  qlik app script get --app '{{ APP }}' > downloaded.qvs
upload: build && reload
  qlik app script set --app '{{ APP }}' build.qvs

reload:
  qlik app reload --app '{{ APP }}'