///$tab L0
SET ThousandSep=',';
SET DecimalSep='.';
SET MoneyThousandSep=',';
SET MoneyDecimalSep='.';
SET MoneyFormat='$ #,##0.00;-$ #,##0.00';
SET TimeFormat='h:mm:ss TT';
SET DateFormat='YYYY-MM-DD';
SET TimestampFormat='YYYY-MM-DD h:mm:ss[.fff] TT';
SET FirstWeekDay=0;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='en-US';
SET CreateSearchIndexOnReload=1;
SET MonthNames='Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec';
SET LongMonthNames='January;February;March;April;May;June;July;August;September;October;November;December';
SET DayNames='Mon;Tue;Wed;Thu;Fri;Sat;Sun';
SET LongDayNames='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

Demo:
LOAD * Inline [
  ID, brand, criteria, assesement
  123, abc, Q9, Y
  145, abc, Q9, Y
  123, abc, P11, Y
  145, abc, P11, N
];

COLORS:
Load * Inline [
  EventTypeC, Colo
  Sale, 'rgb(255, 0, 0)'
];

EVENTS:
Load * Inline [
  Date, EventType, Description
  1, Sale, '500 mg Aspirin'
  2, Email, 'Hello buyer, nice to meet you'
  3, Visit, 'Sales visit'
  4, Sale, '3 mg Avocado'
  4, Visit, 'Avocado explanation'
];
